@echo off
setlocal EnableExtensions EnableDelayedExpansion
chcp 65001 > nul
cd /d "%~dp0..\.."

set PY=.venv\Scripts\python.exe
set SEL_FILE=실행환경\2단계_26B시스템\last_selection.env

if not exist "%PY%" (
    echo [오류] 가상환경 없음. llm_server\00_setup.bat 먼저 실행하세요.
    pause
    exit /b 1
)

cls
echo ================================================
echo   2단계 고사양 데스크톱 - 선택형 서버 시작
echo ================================================
echo.
echo [1차 번역 모델 선택]
echo   1. NLLB-1.3B      (포트 8012)
echo   2. Gemma4-E2B-it  (포트 8001)
echo   3. Gemma4-E4B-it  (포트 8002)
echo.
set /p L1=번호 입력 (1/2/3): 

if "%L1%"=="1" (
    set L1_NAME=NLLB-1.3B
    set L1_TITLE=NLLB-1.3B :8012
    set L1_PORT=8012
    set L1_MODEL=nllb-1p3b
    set L1_CMD=%PY% -m uvicorn nllb_1p3b.server:app --port 8012 --workers 1
    set L1_HEALTH=http://localhost:8012/health
    set PREF_CHAT_NAME=
    set PREF_CHAT_URL=
    set PREF_CHAT_MODEL=
) else if "%L1%"=="2" (
    set L1_NAME=Gemma4-E2B-it
    set L1_TITLE=Gemma4-E2B :8001
    set L1_PORT=8001
    set L1_MODEL=gemma4-e2b
    set L1_CMD=%PY% -m uvicorn gemma4_e2b.server:app --port 8001 --workers 1
    set L1_HEALTH=http://localhost:8001/health
    set PREF_CHAT_NAME=Gemma4-E2B-it
    set PREF_CHAT_URL=http://localhost:8001
    set PREF_CHAT_MODEL=gemma4-e2b
) else if "%L1%"=="3" (
    set L1_NAME=Gemma4-E4B-it
    set L1_TITLE=Gemma4-E4B :8002
    set L1_PORT=8002
    set L1_MODEL=gemma4-e4b
    set L1_CMD=%PY% -m uvicorn gemma4_e4b.server:app --port 8002 --workers 1
    set L1_HEALTH=http://localhost:8002/health
    set PREF_CHAT_NAME=Gemma4-E4B-it
    set PREF_CHAT_URL=http://localhost:8002
    set PREF_CHAT_MODEL=gemma4-e4b
) else (
    echo [오류] 1/2/3 중 하나를 입력하세요.
    pause
    exit /b 1
)

echo.
set /p USE_R2=2차 교정(26B) 실행? (Y/N): 
set USE_R2=%USE_R2:~0,1%

if /I "%USE_R2%"=="Y" (
    echo.
    echo [2차 교정 모델 선택]
    echo   1. Gemma4-26B GGUF  ^(포트 8031^)
    echo   2. Gemma4-E4B-it    ^(포트 8002^)
    echo   3. Gemma4-E2B-it    ^(포트 8001^)
    set /p R2_SEL=번호 입력 ^(1/2/3^): 

    if "!R2_SEL!"=="1" (
        set R2_NAME=Gemma4-26B GGUF
        set R2_TYPE=gguf
        set R2_PORT=8031
        set R2_HEALTH=http://localhost:8031/v1/models
        echo.
        echo [2차 교정 26B 양자화 선택]
        echo   1. IQ3_S ^(기본^)
        echo   2. IQ2_M ^(VRAM 절약^)
        set /p QMODE=번호 입력 ^(1/2^): 

        if "!QMODE!"=="1" (
            set R2_MODEL=IQ3_S
        ) else if "!QMODE!"=="2" (
            set R2_MODEL=IQ2_M
        ) else (
            echo [오류] 1/2 중 하나를 입력하세요.
            pause
            exit /b 1
        )
    ) else if "!R2_SEL!"=="2" (
        set R2_NAME=Gemma4-E4B-it
        set R2_TYPE=uvicorn
        set R2_MODEL=gemma4-e4b
        set R2_TITLE=Gemma4-E4B :8002
        set R2_PORT=8002
        set R2_CMD=%PY% -m uvicorn gemma4_e4b.server:app --port 8002 --workers 1
        set R2_HEALTH=http://localhost:8002/health
    ) else if "!R2_SEL!"=="3" (
        set R2_NAME=Gemma4-E2B-it
        set R2_TYPE=uvicorn
        set R2_MODEL=gemma4-e2b
        set R2_TITLE=Gemma4-E2B :8001
        set R2_PORT=8001
        set R2_CMD=%PY% -m uvicorn gemma4_e2b.server:app --port 8001 --workers 1
        set R2_HEALTH=http://localhost:8001/health
    ) else (
        echo [오류] 1/2/3 중 하나를 입력하세요.
        pause
        exit /b 1
    )
)

if /I "%USE_R2%"=="Y" (
    if /I "!R2_TYPE!"=="gguf" (
        set PREF_CHAT_NAME=Gemma4-26B GGUF
        set PREF_CHAT_URL=http://localhost:8031
        set PREF_CHAT_MODEL=gemma4-26b
    ) else (
        set PREF_CHAT_NAME=!R2_NAME!
        set PREF_CHAT_URL=http://localhost:!R2_PORT!
        set PREF_CHAT_MODEL=!R2_MODEL!
    )
)

echo.
set /p USE_STT=STT(Whisper Turbo) 실행? (Y/N): 
set USE_STT=%USE_STT:~0,1%

echo.
echo ================================================
echo   선택 요약
echo   1차 번역 : !L1_NAME!
if /I "%USE_R2%"=="Y" (
    if /I "!R2_TYPE!"=="gguf" (
        echo   2차 교정 : !R2_NAME! !R2_MODEL!  ^(포트 !R2_PORT!^)
    ) else (
        echo   2차 교정 : !R2_NAME!  ^(포트 !R2_PORT!^)
    )
    
    if "!R2_PORT!"=="!L1_PORT!" (
        echo   [경고] 1차와 2차가 동일 포트 사용! 2차 실행 건너뜁니다.
    )
) else (
    echo   2차 교정 : 사용 안 함
)
if /I "%USE_STT%"=="Y" (
    echo   STT      : Whisper Turbo ^(포트 8021^)
) else (
    echo   STT      : 사용 안 함
)
echo ================================================
echo.

set /p GO=이대로 실행할까요? (Y/N): 
set GO=%GO:~0,1%
if /I not "%GO%"=="Y" (
    echo 취소되었습니다.
    pause
    exit /b 0
)

> "%SEL_FILE%" echo # generated by 서버시작_선택형.bat
>> "%SEL_FILE%" echo L1_NAME=!L1_NAME!
>> "%SEL_FILE%" echo L1_PORT=!L1_PORT!
>> "%SEL_FILE%" echo L1_MODEL=!L1_MODEL!
>> "%SEL_FILE%" echo L1_HEALTH=!L1_HEALTH!
>> "%SEL_FILE%" echo USE_R2=%USE_R2%
>> "%SEL_FILE%" echo R2_NAME=!R2_NAME!
>> "%SEL_FILE%" echo R2_TYPE=!R2_TYPE!
>> "%SEL_FILE%" echo R2_PORT=!R2_PORT!
>> "%SEL_FILE%" echo R2_MODEL=!R2_MODEL!
>> "%SEL_FILE%" echo R2_HEALTH=!R2_HEALTH!
>> "%SEL_FILE%" echo USE_STT=%USE_STT%
>> "%SEL_FILE%" echo NLLB_URL=http://localhost:8012
>> "%SEL_FILE%" echo WHISPER_URL=http://localhost:8021
>> "%SEL_FILE%" echo PREF_CHAT_NAME=!PREF_CHAT_NAME!
>> "%SEL_FILE%" echo PREF_CHAT_URL=!PREF_CHAT_URL!
>> "%SEL_FILE%" echo PREF_CHAT_MODEL=!PREF_CHAT_MODEL!

echo [기록] 선택값 저장: %SEL_FILE%

echo.
echo [1] 1차 번역 서버 시작: !L1_NAME!
start "!L1_TITLE!" cmd /k "!L1_CMD!"
timeout /t 3 /nobreak > nul

if /I "%USE_R2%"=="Y" (
    if "!R2_PORT!"=="!L1_PORT!" (
        echo [2] 2차 교정 시작 건너뜀: 1차와 동일 포트 ^(!R2_PORT!^)
    ) else if /I "!R2_TYPE!"=="gguf" (
        echo [2] 2차 교정 서버 시작: !R2_NAME! !R2_MODEL!
        start "Gemma4-26B GGUF !R2_MODEL! :8031" cmd /k ^
            "%PY% llama_gguf\start.py --model !R2_MODEL! --port 8031 --ngl 99"
        timeout /t 5 /nobreak > nul
    ) else (
        echo [2] 2차 교정 서버 시작: !R2_NAME!
        start "!R2_TITLE!" cmd /k "!R2_CMD!"
        timeout /t 3 /nobreak > nul
    )
)

if /I "%USE_STT%"=="Y" (
    if /I "%USE_R2%"=="Y" (
        echo [3] STT 서버 시작: Whisper Turbo
    ) else (
        echo [2] STT 서버 시작: Whisper Turbo
    )
    start "Whisper Turbo :8021" cmd /k ^
        "%PY% -m uvicorn whisper_turbo.server:app --port 8021 --workers 1"
)

echo.
echo ================================================
echo   서버 로딩 중... 30~90초 소요
echo   1차 번역 : !L1_HEALTH!
if /I "%USE_R2%"=="Y" (
    echo   2차 교정 : !R2_HEALTH!
)
if /I "%USE_STT%"=="Y" (
    echo   STT      : http://localhost:8021/health
)
echo ================================================
echo.
echo 데모 테스트: 데모테스트.bat 실행
echo EPUB 번역 GUI: EPUB번역_GUI.bat 실행
echo.
pause
